### ISSUE TITLE
If this is revised code, why a new repository?

### ISSUE THREAD

**Issue by ScriptAutomate** [udacity/AIPND-revision#5]
I'm wondering why this repository exists, instead of as applied revisions to https://github.com/udacity/AIPND?

I see that the other repository is still being updated, as of January, so it doesn't look like this "revised" repo is meant to be a replacement. It isn't clear in the README.md why this is a different repository when a new branch / merge into the other repo would retain the history to show what was revised (if needed).

**Comment by ronny-udacity** [comment]
This repo contains the updated project only in AIPND. 
For the main repo for this Nanodegree program, please refer to https://github.com/udacity/AIPND.
