### ISSUE TITLE
Installing requirements.txt

### ISSUE THREAD

**Issue by JCherryhomes** [udacity/AIPND-revision#7]
Attempting to install requirements.txt running `pip3 install -r requirements.txt` as stated in the instructions.

Receive the following error: 

> ERROR: No matching distribution found for torch==0.4.0 (from -r requirements.txt (line 1))

Running Python 3.8 on Windows 10

**Comment by ronny-udacity** [comment]
Thanks for reporting the issue. 

Please refer to this StackOverflow discussion pip torch installation on Windows: https://stackoverflow.com/questions/60944201/how-to-install-torch-0-4-1-on-windows-10

> pip install torch===0.4.0 -f https://download.pytorch.org/whl/torch_stable.html
Or, on the `requirements.txt` line 1, please add "-f https://download.pytorch.org/whl/torch_stable.html"
